# :: c a u s t i c  c o m p u t i n g ::
# ~/.config/kitty/kitty.conf
# host: $HOSTNAME
# Kitty terminal configuration file
# created <2026-09-25> :: last modified <2026-09-25T14:24-06:00>
#
# --- BEGIN CONFIGURATION FILE ---

# :: shell ::
shell /usr/bin/zsh

# :: mod keys ::
kitty_mod ctrl+shift

# :: Theme (Symfonic) ::
include current-theme.conf

# :: fonts ::
font_family          JetBrains Mono Slashed
bold_font            JetBrains Mono Slashed Bold
italic_font          JetBrains Mono Slashed Italic
bold_italic_font     JetBrains Mono Slashed Bold Italic
font_size 14

# :: transparency ::
background_opacity 0.80

# :: layout ::
enabled_layouts tall

# :: tabs ::
tab_bar_style powerline
tab_activity_symbol *

# :: map keys ::
map ctrl+F1 new_window_with_cwd
map ctrl+F2 launch --cwd=current /usr/bin/vim
map ctrl+F3 launch --cwd=current /usr/bin/nvim

# --- END CONFIGURATION FILE ---
